# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x07\n\x05\x45mpty\"1\n\x0b\x41\x63\x63ountInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\">\n\x03Msg\x12\x14\n\x0csrc_username\x18\x01 \x01(\t\x12\x14\n\x0c\x64st_username\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t2\xa9\x02\n\x07\x43hatApp\x12\x32\n\rCreateAccount\x12\x11.chat.AccountInfo\x1a\x0e.chat.Response\x12\x31\n\x0cLoginAccount\x12\x11.chat.AccountInfo\x1a\x0e.chat.Response\x12+\n\x0cListAccounts\x12\x0b.chat.Empty\x1a\x0e.chat.Response\x12\x32\n\rDeleteAccount\x12\x11.chat.AccountInfo\x1a\x0e.chat.Response\x12%\n\x0bSendMessage\x12\t.chat.Msg\x1a\x0b.chat.Empty\x12/\n\rMessageStream\x12\x11.chat.AccountInfo\x1a\t.chat.Msg0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _ACCOUNTINFO._serialized_start=29
  _ACCOUNTINFO._serialized_end=78
  _RESPONSE._serialized_start=80
  _RESPONSE._serialized_end=119
  _MSG._serialized_start=121
  _MSG._serialized_end=183
  _CHATAPP._serialized_start=186
  _CHATAPP._serialized_end=483
# @@protoc_insertion_point(module_scope)
